/*Try statements that can be nested via
 * calls to methods*/
public class MethNestTry {
	static void nesttry(int a) {
		try {
			/**
			 * If one command-line arg is used,
			 * then a divide by zero exception
			 * will be generated by the following code
			 */
			if (a==1) {
				a=a/(a-a);//division by zero
			}
			
			/*
			 * If two command-line arguments are used,
			 * then generate an out-of-bounds exception
			 */
			if (a==2) {
				int c[] = { 1 };
				c[2] = 99; //generate out of bounds exception
			}
		} catch (ArrayIndexOutOfBoundsException e) {
			// TODO: handle exception
			System.out.println("Array-index-out-of-bounds: "+e);
		}
	}
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
			int a =args.length;
			/**
			 * If one command-line arg is used,
			 * then a divide by zero exception
			 * will be generated by the following code
			 */
			int b= 42/a; // generates a divide-by-zero exception
			System.out.println("a = "+a);
			nesttry(a);
		} catch (ArithmeticException e) {
			// TODO: handle exception
			System.out.println("Divide by 0: "+e);
		}
	}
}