//An example of nested try statements
class NestTry {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
			int a= args.length;
			/*If no command line args are present,
			 * the following statement
			 * generates a divide by zero expression*/
			int b=42/a;
			System.out.println("a: "+a);
			
			try { // nested try block
				/*If one command line argument is used
				 * then a divide-by-zero exception
				 * is generated by the following code.*/
				System.out.println("ahd");
				if (a==1) {
					a=a/(a-a);
				}
				/*If two command line arguments are used
				 * then an array out of bounds exception
				 * is generated by the following code.*/
				if (a==2) {
					int c[]= { 1 };
					c[42]=99;//generate an out-of-bounds exception
				}
			} catch (ArrayIndexOutOfBoundsException e) {
				// TODO: handle exception
				System.out.println("Array out of bounds exception: "+e);
			}
		} catch (ArithmeticException e) {
			// TODO: handle exception
			System.out.println("No command line arguments provided");
			System.out.println("Error: "+e);
		}
	}

}
